---
- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
- name: Rename 127.0.0.1 name in /etc/hosts
  vars:
    comment: '# added by ansible'
  lineinfile:
    dest: /etc/hosts
    regexp: "127[.]0[.]0[.]1.*"
    line: "127.0.0.1  {{ ansible_hostname }}.{{ domain }} {{ ansible_hostname }}  localhost {{ comment }}"
    state: present
    backup: yes
- name: Rename 127.0.1.1 name in /etc/hosts
  vars:
    comment: '# added by ansible'
  lineinfile:
    dest: /etc/hosts
    regexp: "127[.]0[.]1[.]1.*"
    line: "127.0.1.1  {{ ansible_hostname }}.{{ domain }} {{ ansible_hostname }}  {{ comment }}"
    state: present
    backup: yes